
%.bin: %.asm
	nasm -f bin $< -o $@

master.img:boot.bin loader.bin
	yes | bximage -q -hd=16 -func=create -sectsize=512 -imgmode=flat master.img 
	dd if=boot.bin of=master.img bs=512 count=1 conv=notrunc
	dd if=loader.bin of=master.img bs=512 count=4 seek=2 conv=notrunc

# .PHINY: usb
# usb: boot.bin /dev/sdb
# 	sudo dd if=/dev/sdb of=tmp.bin bs=512 count=1 conv=notrunc	
# 	cp tmp.bin usb.bin
# 	sudo rm tmp.bin
# 	dd if=boot.bin of=usb.bin bs=446 count=1 conv=notrunc
# 	sudo dd if=usb.bin of=/dev/sdb bs=512 count=1 conv=notrunc
# 	rm usb.bin	


.PHINY: clean
clean:
	rm -rf *.bin
	rm -rf *.img

.PHINY: bochs
bochs: master.img
	bochs -q
